Audio codec: Fix a compiler error.
packages/apps/Settings/src/com/android/settings/development/bluetooth/BluetoothCodecDialogPreferenceController.java:207: error: duplicate case label
            case SOURCE_CODEC_TYPE_OPUS: // TODO update in U

Signed-off-by: spezi77 <spezi7713@gmx.net>